name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint  # Assuming you have a linting script in package.json

      - name: Run unit tests
        run: npm test  # Assuming you have a test script in package.json

      - name: Build the application
        run: npm run build  # Assuming you have a build script in package.json

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./tests/results/  # Path to your test results
